apiVersion: v1
kind: Service
metadata:
    name: camunda-zeebe-gateway-lb
    namespace: default
spec:
    ports:
    - name: http
      port: 9600
      protocol: TCP
      targetPort: 9600
    - name: http2
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: http3
      port: 443
      protocol: TCP
      targetPort: 8080
    - name: gateway
      port: 26500
      protocol: TCP
      targetPort: 26500
    selector:
        app: camunda-platform
        app.kubernetes.io/component: zeebe-gateway
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: camunda-zeebe-gateway
        app.kubernetes.io/part-of: camunda-platform
    type: LoadBalancer